include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error

  exclude:
    - '**.freezed.dart'
    - '**.g.dart'

linter:
  rules:
    # Allow good old UPPER_CASE_CONSTANT_VARIABLE_NAMES
    constant_identifier_names: false
    non_constant_identifier_names: false

    # We dont want to use a logging framework (yet)
    avoid_print: false
