name: p2panda
repository: https://github.com/p2panda/meli

packages:
  - packages/*

scripts:
  analyze:
    exec: flutter analyze .
    description: Analyze all Dart packages for code errors and warnings.

  format:
    exec: dart format .
    description: Format all Dart packages according to linter settings.

  release:
    run: bash scripts/release.sh
    packageFilters:
      flutter: true
      scope: "*app*"
    description: Compile .apk builds for all architectures

  build:
    run: bash scripts/build.sh
    description: Compile native p2panda library for Android.

  clear:
    run: bash scripts/clear.sh
    description: Remove artifacts which got created after building.
